-- ============================================================================
-- Migration: 20261015090000_f3c_billing_automation.sql
-- Module: F3c — Billing in jobs: daily transitions, notices and payout
--         reports (plano F3, decision 4; D-PA-13; especificação de
--         parceiros §3)
--
-- Maintenance Rationale:
-- 1. `public.billing_settings`: one row with the provisional terms of
--    decision 4 (3 days of tolerance after the period end before "em
--    atraso", 7 more days before "suspensa"). Platform billing edits it.
-- 2. `public.notification_deliveries`: every notice, unique per
--    idempotency key, with its outcome (`skipped` while no e-mail provider
--    exists, D-PA-08). Read by the platform and by the partner it concerns.
-- 3. `public.payout_reports`: totals per partner and month, generated by a
--    job, unique per partner and period.
-- 4. Platform jobs act without a user, as `app_worker`, through narrow
--    policies of their own: read subscriptions and the few columns notices
--    need (column grants), move subscriptions from active to past due and
--    from past due to suspended (the P5m trigger still validates every
--    transition), and write deliveries and reports. The web runtime cannot
--    become app_worker, so none of this reaches it. Jobs requested by users
--    keep running as app_runtime in the requester's context (F3a).
-- 5. Platform jobs audit what they change as a worker service (no user,
--    no workspace).
-- Owner app_migrations, ENABLE + FORCE RLS, no grants to anon/authenticated.
-- The settings row is seeded before RLS is enabled.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Billing settings
-- ----------------------------------------------------------------------------
create table public.billing_settings (
  id                  smallint primary key default 1 check (id = 1),
  past_due_after_days integer not null default 3 check (past_due_after_days between 0 and 60),
  suspend_after_days  integer not null default 7 check (suspend_after_days between 1 and 90),
  provisional         boolean not null default true,
  updated_by          uuid references public.profiles(id) on delete set null,
  updated_at          timestamptz not null default now()
);

insert into public.billing_settings (id) values (1);

alter table public.billing_settings owner to app_migrations;
revoke all on public.billing_settings from public, anon, authenticated;
alter table public.billing_settings enable row level security;
alter table public.billing_settings force row level security;

create trigger billing_settings_touch_updated_at
  before update on public.billing_settings
  for each row execute function private.touch_updated_at();

create policy billing_settings_select on public.billing_settings
  for select to app_runtime
  using (private.can_read_platform_billing() or private.can_read_partner_billing());

create policy billing_settings_update on public.billing_settings
  for update to app_runtime
  using (private.can_manage_platform_billing())
  with check (
    private.can_manage_platform_billing()
    and updated_by = private.context_uuid('app.user_id')
  );

create policy billing_settings_worker_select on public.billing_settings
  for select to app_worker
  using (true);

grant select, update on public.billing_settings to app_runtime;
grant select on public.billing_settings to app_worker;

-- ----------------------------------------------------------------------------
-- 2. Notification deliveries
-- ----------------------------------------------------------------------------
create table public.notification_deliveries (
  id              uuid primary key default gen_random_uuid(),
  partner_id      uuid not null references public.partners(id) on delete cascade,
  event_type      text not null check (event_type ~ '^[a-z]+(\.[a-z_]+)+$' and length(event_type) <= 80),
  recipient_email text not null check (length(recipient_email) between 3 and 254),
  subject         text not null check (length(subject) between 1 and 200),
  idempotency_key text not null unique check (length(idempotency_key) between 1 and 200),
  related_id      uuid,
  status          text not null default 'pending' check (status in ('pending', 'sent', 'skipped', 'failed')),
  reason          text check (reason is null or length(reason) <= 200),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index notification_deliveries_partner_idx
  on public.notification_deliveries (partner_id, created_at desc);

alter table public.notification_deliveries owner to app_migrations;
revoke all on public.notification_deliveries from public, anon, authenticated;
alter table public.notification_deliveries enable row level security;
alter table public.notification_deliveries force row level security;

create trigger notification_deliveries_touch_updated_at
  before update on public.notification_deliveries
  for each row execute function private.touch_updated_at();

create policy notification_deliveries_select on public.notification_deliveries
  for select to app_runtime
  using (
    private.can_read_platform_billing()
    or (partner_id = private.current_partner_id() and private.can_read_partner_billing())
  );

create policy notification_deliveries_worker_select on public.notification_deliveries
  for select to app_worker
  using (true);

create policy notification_deliveries_worker_insert on public.notification_deliveries
  for insert to app_worker
  with check (status = 'pending');

create policy notification_deliveries_worker_update on public.notification_deliveries
  for update to app_worker
  using (status = 'pending')
  with check (status in ('sent', 'skipped', 'failed'));

grant select on public.notification_deliveries to app_runtime;
grant select, insert, update on public.notification_deliveries to app_worker;

-- ----------------------------------------------------------------------------
-- 3. Payout reports
-- ----------------------------------------------------------------------------
create table public.payout_reports (
  id                 uuid primary key default gen_random_uuid(),
  partner_id         uuid not null references public.partners(id) on delete cascade,
  period_start       date not null,
  period_end         date not null check (period_end > period_start),
  payments_count     integer not null check (payments_count >= 0),
  received_cents     integer not null check (received_cents >= 0),
  refunded_cents     integer not null check (refunded_cents >= 0),
  platform_net_cents integer not null,
  partner_net_cents  integer not null,
  generated_at       timestamptz not null default now(),
  unique (partner_id, period_start)
);

alter table public.payout_reports owner to app_migrations;
revoke all on public.payout_reports from public, anon, authenticated;
alter table public.payout_reports enable row level security;
alter table public.payout_reports force row level security;

create policy payout_reports_select on public.payout_reports
  for select to app_runtime
  using (
    private.can_read_platform_billing()
    or (partner_id = private.current_partner_id() and private.can_read_partner_billing())
  );

create policy payout_reports_worker_select on public.payout_reports
  for select to app_worker
  using (true);

create policy payout_reports_worker_insert on public.payout_reports
  for insert to app_worker
  with check (true);

grant select on public.payout_reports to app_runtime;
grant select, insert on public.payout_reports to app_worker;

-- ----------------------------------------------------------------------------
-- 4. What platform jobs read and change as app_worker
-- ----------------------------------------------------------------------------
create policy subscriptions_worker_select on public.subscriptions
  for select to app_worker
  using (true);

-- Only arrears and suspension; the guard trigger validates the transition
-- and keeps the terms frozen.
create policy subscriptions_worker_update on public.subscriptions
  for update to app_worker
  using (status in ('active', 'past_due'))
  with check (status in ('past_due', 'suspended'));

grant select, update on public.subscriptions to app_worker;

create policy payments_worker_select on public.payments
  for select to app_worker
  using (true);

grant select (id, partner_id, kind, amount_cents, platform_share_cents, partner_share_cents, paid_on)
  on public.payments to app_worker;

create policy partners_worker_select on public.partners
  for select to app_worker
  using (true);

grant select (id, name, status, is_house) on public.partners to app_worker;

create policy partner_domains_worker_select on public.partner_domains
  for select to app_worker
  using (status = 'active');

grant select (host, partner_id, kind, status) on public.partner_domains to app_worker;

create policy partner_billing_profiles_worker_select on public.partner_billing_profiles
  for select to app_worker
  using (true);

grant select (partner_id, billing_email) on public.partner_billing_profiles to app_worker;

create policy partner_members_worker_select on public.partner_members
  for select to app_worker
  using (role = 'partner_owner' and status = 'active');

grant select (partner_id, email, role, status, created_at) on public.partner_members to app_worker;

create policy organizations_worker_select on public.organizations
  for select to app_worker
  using (true);

grant select (id, name, partner_id) on public.organizations to app_worker;

-- ----------------------------------------------------------------------------
-- 5. Audit of automatic changes
-- ----------------------------------------------------------------------------
-- A platform job records what it changed as a service of the worker, never
-- in a user's or workspace's name, at the current time.
create policy audit_events_worker_insert on public.audit_events
  for insert to app_worker
  with check (
    actor_principal_type = 'service'
    and actor_user_id is null
    and represented_user_id is null
    and grant_id is null
    and workspace_id is null
    and origin = 'worker'
    and occurred_at >= (now() - interval '5 minutes')
    and occurred_at <= (now() + interval '1 minute')
  );

grant insert on public.audit_events to app_worker;
